### ISSUE TITLE
Does reading one CSR mean that you should be able to read any CSR? (ditto Write, ditto FPR)

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#100]
We should clarify, if you have one CSR abstract command which fails, does that mean all CSRs would also fail

**Comment by mwachs5** [comment]
https://github.com/riscv/riscv-openocd/pull/79 Seems to make this assumption since it caches the result of the first time it tries to read/write CSRs/FPRs. Is that the conclusion?

**Comment by timsifive** [comment]
It's just something that I implemented until the spec makes clear what I should do. Using 2 bits per CSR seemed a little excessive.

In any case, what I implemented is safe as long as a program buffer exists to fall back on.
