### ISSUE TITLE
A typo in [5.4. Native Triggers]

### ISSUE THREAD

**Issue by en-sc** [riscv/riscv-debug-spec#1015]
There is the following line:

> This might leave the hart unable to resume normal execution because state such as and would be overwritten.

It seems to contain a typo, though I can't figure out what the typo is.

**Comment by pdonahue-ventana** [comment]
Here was the original text: https://github.com/riscv/riscv-debug-spec/blob/latex/Sdtrig.tex#L179

So it should probably be:
```
This might leave the hart unable to resume normal execution because state such as `mcause` and `mepc` would be overwritten.
```
