### ISSUE TITLE
How to halt or resume multiple harts simultaneously?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv/riscv-debug-spec#1016]
For multi-hart System-on-Chip (SoC) system, which every Debug Module (DM) corresponds to one hart, how can multiple harts be simultaneously halted or resumed synchronously?
Thanks!

**Comment by en-sc** [comment]
https://openocd.org/doc-release/html/Config-File-Guidelines.html
Section [6.3.4 Define CPU targets working in SMP]

**Comment by en-sc** [comment]
AFAIU, the debug spec does not cover this. The functionality you need may be supported by a custom mechanism. One should also be mindful whether the DMs share a single TAP (more precisely, DMs are on the same DMI bus) or not.

**Comment by zhangdujiao** [comment]
> One should also be mindful whether the DMs share a single TAP (more precisely, DMs are on the same DMI bus) or not.

thanks. 
yes,  assuming all DMs are on the same DMI bus.

**Comment by rtwfroody** [comment]
The debug spec doesn't say. You could probably rig something up with halt groups, resume groups, and external triggers. In this case the external triggers would somehow connect to the harts on other DMs. Section 3.6 talks about the basic mechanisms.
