### ISSUE TITLE
Minor typo + Cannot open PR

### ISSUE THREAD

**Issue by albert-azcarate** [riscv/riscv-debug-spec#1041]
Hi, I've found a minor typo and I wanted to open a PR with the fix but I cannot push the branch due to not having permissions

**Comment by rtwfroody** [comment]
The way to do this is to fork our repo, push your fix to a branch in that
fork, and then make the PR.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
explains it in more detail.

**Comment by albert-azcarate** [comment]
[PR here](https://github.com/riscv/riscv-debug-spec/pull/1042), I close this issue
