### ISSUE TITLE
dcsr.cetrig should be WARL

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-debug-spec#1054]
Hi,

I asked a question about the Double Trap in its github repos (please see https://github.com/riscv/riscv-double-trap/issues/53) and the outcome of that was that dcsr.cetrig should be WARL instead of R/W.

Best regards,
Arjan

**Comment by ved-rivos** [comment]
Addressed in https://github.com/riscv/riscv-debug-spec/pull/1051
