### ISSUE TITLE
Can DMI BUS support 64bits access?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv/riscv-debug-spec#1060]
3.1 Debug Module Interface (DMI)
"The DMI uses between 7 and 32 address bits. Each address points at a single 32-bit register that can be read or written."

And, A.3 Debug Module Interface Signals
Table A.1 shows the width of REQ ADDRESS is abits, which is 6 bits max and support max value 64.
So, the max bits of access address is 32 or 64?
If 64, the next DM in the DMI address space is given in nextdm. But the width of nextdm is 32 only, not 64. 

How to sovle the problem if we have a large address space, and multiple DMs are integrated in multiple die, and only 32bits address cannot be enough for accessing all the DMs.

**Comment by en-sc** [comment]
> And, A.3 Debug Module Interface Signals Table A.1 shows the width of REQ ADDRESS is abits, which is 6 bits max and support max value 64. So, the max bits of access address is 32 or 64?

AFAIK, to represent 32 one needs 6 bits ($32_{10} = 100000_2$). To represent 64, 7 bits are needed. Therefore, IMHO, specification is consistent in this regard -- DMI address is no longer than 32 bits.

> How to sovle the problem if we have a large address space, and multiple DMs are integrated in multiple die, and only 32bits address cannot be enough for accessing all the DMs.

Each DM uses addresses up to `0x7f` (with regard to base address). So 32-bit address space should fit up to  $2^{32 - 7} \approx 3.4 \times 10^7$ DMs. With each DM accommodating up to $2^{20} \approx 1.0 \times 10^6$ harts, one could fit up to $3.4 \times 10^{13}$ harts on a single DMI bus.

IMHO, this should be enough.
