### ISSUE TITLE
DMACTIVE deactivation

### ISSUE THREAD

**Issue by Mustafa-abdelhamid** [riscv/riscv-debug-spec#1082]
In the RISC-V Debug Specification (0.13),  `dmactive` is set to 0x1 when the debugger connects, activating the Debug Module (DM). However, there is no guidance on resetting dmactive to 0x0 when the debugger disconnects and the probe is detached. To ensure consistent deactivation,  The specification may recommend that debugger implementations set dmactive to 0x0 upon disconnection.

**Comment by pdonahue-ventana** [comment]
Note that 0.13 is more than 5 years old and no further changes will be made to that.  [Language was added](https://github.com/riscv/riscv-debug-spec/blob/main/debug_module.adoc?plain=1#L229) to the current debug spec in mid-2021 that says that debuggers should resume all harts and then clear dmactive:
> Debuggers should use resumereq to explicitly resume harts before clearing dmactive and disconnecting.

If you don't clear dmactive then I don't think that anything bad would happen (other than wasting power).
