### ISSUE TITLE
The privilege level of Debug Mode

### ISSUE THREAD

**Issue by zhangdujiao** [riscv/riscv-debug-spec#1083]
Whether a core can access any address space after entering the debug mode?
Is the privilege level of Debug Mode is even higher than M level?

**Comment by pdonahue-ventana** [comment]
See [section 4.1](https://github.com/riscv/riscv-debug-spec/blob/main/Sdext.adoc?plain=1#L32) of the debug spec.  "All operations are executed with machine mode privilege, except that additional Debug Mode CSRs are accessible" which means that D can do everything that M can do plus more, much like M can do more than S and S can do more than U.  That basically means that D is a higher level than M.
