### ISSUE TITLE
Does the hart have to halt at first instruction out of reset when set halt-on-reset bit?

### ISSUE THREAD

**Issue by lz-bro** [riscv/riscv-debug-spec#1094]
From debug spec 1.0 "When a hart’s halt-on-reset request bit is set, the hart will immediately enter debug mode on the next deassertion of its reset"
There doesn't seem to be any mention of what the dpc must be.

**Comment by pdonahue-ventana** [comment]
Section 4.7 says: "When a hart halts ... dpc is set to the next instruction that should be executed."  Therefore, dpc points to the reset vector because it is the next instruction that would have executed if we didn't halt.
