### ISSUE TITLE
Clarify Scope : Virtual Memory, U/S/H modes

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#110]
Question from today's call was just about whether this document's scope handles things like virtual memory translation, debugging multi-threaded OS systems, etc. We should clarify where this spec ends and OS-level debuggers begin.

**Comment by timsifive** [comment]
Immediate thoughts:
1. Debug Mode only deals in physical addresses, so any virtual address translation is left to the debugger.
2. Debug Mode exposes harts. If there is an OS with threads (which potentially move from hart to hart) that's a problem for the debugger.
