### ISSUE TITLE
Say what version of the ISA Spec(s) this Debug Spec should be read with

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#115]
For example, there may be something mentioned in a Priv spec which is removed in later specs, so then reading the Debug spec is unclear what it is referring to

**Comment by poweihuang17** [comment]
IMO, we should follow the latest iSA spec for this debug spec. If anything is async with the latest ISA spec, we should change our debug spec to coordinate with it.

**Comment by poweihuang17** [comment]
I remembered this was referring to configuration string.

**Comment by poweihuang17** [comment]
Additional problem that was arising today: What if people implement custom priv spec.

**Comment by mwachs5** [comment]
Closed by #174
