### ISSUE TITLE
Signed address in dmstatus of HARTINFO

### ISSUE THREAD

**Issue by poweihuang17** [riscv/riscv-debug-spec#136]
Need to clarify the center, as that is a signed address.

**Comment by mwachs5** [comment]
Right. The intention was that when doing something like:

```
lw s0, <dataaddr>(x0)
```

`s0` would then contain the value of in  the Debug Module register `DATA[0]`. 

So, if `dataaddr` is a negative number, the "wraparound" value might need to be understood in case someone decided they wanted to construct this address in a different way, like:

```
li s1, <0 - dataaddr>
lw s0, s1
```

It may be unclear what should be in `s1`.

**Comment by mwachs5** [comment]
@timsifive didn't you make a change to clarify this?

**Comment by timsifive** [comment]
Yes, change 02f1aac5.
