### ISSUE TITLE
Is 4 bits enough for the version number in DMSTATUS?

### ISSUE THREAD

**Issue by poweihuang17** [riscv/riscv-debug-spec#137]

**Comment by timsifive** [comment]
The usual solution is that when we get to version 15, we add bits somewhere else and then say that if this field is 15 then to look there. My hope is that it will be quite some time before we get that far.

**Comment by poweihuang17** [comment]
Yeah. It could be. It's an issue that Rishiyur pointed out in the meeting. He doesn't want the 4 bit to be a constraint in the future, and the register do have place to increase from 4 bits. I think your solution will be better, as it's a software approach.
Just add a feedback from what I was asked when I'm interviewed by MediaTek folks for a graduate level job. After I tell them about all the implementation, including Syntacore(0.90), SiFive(0.13), ???(0.11), Bluespec (Custom approach), they're wondering why there are so many versions given that we have a standard. I replied it by a compatibility of gdb, but again, if we're satiesfied with gdb level compatibility, the meaning of the standard would be ambiguous. I guess in the end it will be better for all 3rd party companies and IP companies to resolve to less than 4 versions.

**Comment by timsifive** [comment]
Rishiyur seems satisfied with this explanation as well. E-mail from:"Rishiyur Nikhil" subject:"[Debug] Detailed comments on latest draft of debug spec":
> ...
> >   > Section 3.10, Section on dmstatus
> >   >
> >   > Are 4 bits enough for future evolution of the 'version' field? (dmstatus has many unused bits that could be reserved now for a wider 'version' field)
>
> >   When we get to version 15, we'll say that 15 means to look somewhere else for the true version. I don't foresee us getting there any time soon.
> 
> Ok.
> ...

Can we close this issue?

**Comment by poweihuang17** [comment]
Yes. I think we could.

**Comment by poweihuang17** [comment]
I'll close that now.

**Comment by poweihuang17** [comment]
Subversion within 0.13 cause this issue to be reopened...
See Markus's email.

**Comment by mwachs5** [comment]
related to #188

**Comment by timsifive** [comment]
Closing due to lack of interest/activity.
