### ISSUE TITLE
inconsistent error protocol between abstractcs and sbcs

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-debug-spec#139]
From Nikhil:
>  - Some handshakes involve commands in one register with error status
>       in another register (e.g., 'control' and 'abstractcs'). After an
>       error, the error has to be cleared in the latter register before
>       the next comand on the former register, requiring an extra
>       transaction from the debugger.
>
>  - Some handshakes involve commands and error status in the same
>       register (e.g., 'sbcs'). After an error, the error can be
>       cleared simultaneously with the next command.

Note that control's errors are completely different from both of those, and (I think) with good reason.

**Comment by timsifive** [comment]
If we're making backwards incompatible changes to System Bus Access to address #150 then I'm fine also breaking up sbcs into sbcontrol and sbstatus. (I believe we have register space for it.) Otherwise I'm inclined to leave things as is.

**Comment by timsifive** [comment]
I'm changing my mind on this.
abstractcs puts everything in one register. We also have dmcontrol and dmstatus. The reason the latter are split up is that all the bits don't fit in one register. I don't see a good reason to make a second register because in one case we were forced to.

**Comment by mwachs5** [comment]
I agree, especially since we are already using up a lot of registers for SBaccess
