### ISSUE TITLE
v13 vs master branches

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#202]
Why are there both `v13` and `master` branches (I believe the default working branch used to be `v13`). Should we just delete the `v13` branch? I think it is confusing at the moment. I assume this is related to #188, but not clear what the intended usage of the branches is right now.

**Comment by timsifive** [comment]
`master` refers to the OpenOCD master. `riscv` is the RISC-V mainline. `v13` can be deleted.

**Comment by timsifive** [comment]
I think I created `0.13` when messing with versioning. It can be deleted AFAIC.

**Comment by timsifive** [comment]
github won't let me delete it because it's protected. I'm not sure how a branch gets that status.

**Comment by mwachs5** [comment]
I unprotected it (via Settings->Branches). And protected `master`

**Comment by timsifive** [comment]
I deleted it.

**Comment by mwachs5** [comment]
hm that seems to have had the side effect of deleting all PRs being made against it

**Comment by timsifive** [comment]
:-( Were there any important ones? Presumably people can recreate them if they still have them in their own git repo.

**Comment by mwachs5** [comment]
They are just Closed (my 'deleted' was misleading). They can be re-opened against the `master` branch as desired. I did that for #185
