### ISSUE TITLE
DPC Clobbering clarification

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#233]
From Ben Horgan:
3.6: How does software know if the implementation clobbers the dpc when executing the program buffer?

**Comment by mwachs5** [comment]
The spec already says 
```
Executing the Program Buffer may clobber \Rdpc. If that is the case, it must be
possible to read/write \Rdpc using an abstract command with \Fpostexec not set.
The debugger must attempt to save \Rdpc between halting and
executing a Program Buffer, and then restore \Rdpc before leaving Debug Mode.
```

That text was already edited to address the same question. Not sure how it can be made more clear.

**Comment by timsifive** [comment]
The answer is: The debug software doesn't know, which is why it must attempt to save/restore dpc.

But I'm not sure how to add that to the spec without cluttering it up.

**Comment by timsifive** [comment]
I think we should close this issue.
