### ISSUE TITLE
SB Access: should there be an error code for unsupported SB Access size?

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#252]
Currently the spec calls out SB error code 3 to be "some other error, e.g. alignment". What about the error case when you try to do an unsupported sbaccess size? Does that fall under "some other error"? It seems like a common enough case that it should be specifically tied to some value, even if it is also 3.

**Comment by mwachs5** [comment]
Oh I see you tried to clarify this here: https://github.com/riscv/riscv-debug-spec/pull/203/commits/b8eb62a53e9616e078d71ee264cf73528ee87ef2

But that is not really in a place that someone might look for it when implementing SBERROR logic

**Comment by mwachs5** [comment]
But then it is also unclear the priority of these errors. What if I send a misaligned access to an inaccessible address, which error type should I return? Either is fine?

**Comment by timsifive** [comment]
I'm updating \Fsberror to also mention unsupported access size for 3.

**Comment by mwachs5** [comment]
Resolved by #254
