### ISSUE TITLE
Can hartsel be changed while an abstract command is executing?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-debug-spec#315]
Is changing `hartsel` forbidden while `abstractcs.busy` is set?  Or must a DM support the possibility of `hartsel` being changed (perhaps to examine `hartinfo` or one of the halt summary registers) while an abstract command is still executing for a hart?

**Comment by timsifive** [comment]
You can't change `hartsel` while it's being used. Please let me know if #322 adequately explains that.
