### ISSUE TITLE
What cmderr when an abstract command attempts to access a nonexistent register?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-debug-spec#317]
If an abstract command attempts to access a hart register that doesn't exist, what is the correct setting for `abstractcs.cmderr`?  Should it be "not supported" (2), "exception" (3), or "other" (7)?

**Comment by timsifive** [comment]
Seems like it should be "exception" or "other." "not supported" implies the abstract command isn't supported, but it is in this case. I'm inclined to mandate "exception."

**Comment by jhauser-us** [comment]
I agree that's probably best.
