### ISSUE TITLE
What happens if the hart array mask register is changed while hartreset is 1?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-debug-spec#320]
If `dmcontrol.hartreset` is written with a 1, and then the set of selected harts is changed by modifying the hart array mask register, how does this affect reset for both the previously selected harts (no longer selected) and the newly selected harts?  

(A similar question could be asked about writing `dmcontrol` with `hartreset` set, first for one value of `hartsel`, and then again with a different value of `hartsel`, without zeroing `hartreset` in between.)

**Comment by timsifive** [comment]
I'm inclined to say that debuggers mustn't do that. It's not a useful feature, and different implementations may prefer different behaviors.

What do you think?

**Comment by jhauser-us** [comment]
Fine by me.

**Comment by timsifive** [comment]
BTW, can you let me know your name, so I can thank you in the preface?

**Comment by jhauser-us** [comment]
My real-life name is John Hauser.  I've updated my GitHub profile, so maybe it'll show now.
