### ISSUE TITLE
Abstract data reg 0 starting at 0x04

### ISSUE THREAD

**Issue by zarubaf** [riscv/riscv-debug-spec#343]
Is there a specific reason why you put `data0` at address `0x04` and not on the base `0x0`? The choice seems a bit strange to me.

**Comment by timsifive** [comment]
There's no good reason, besides historical. At one point addresses 0-3 were
used, and there were only a few possible data registers.

**Comment by zarubaf** [comment]
Aligning it on a power of two would make the decoding more efficient (potentially reserving `data12`-`15` for future use).

**Comment by timsifive** [comment]
I'm afraid that ship has sailed. If it makes you feel better, 4 words is enough to support all currently specified abstract commands up to RV64, and with so few words there's no decoding benefit.

**Comment by zarubaf** [comment]
(y)
