### ISSUE TITLE
[Style] Move table 3.6 to first reference

### ISSUE THREAD

**Issue by zarubaf** [riscv/riscv-debug-spec#344]
When implementing the abstract command I actually only implemented GPR read and write at first because I didn't see the table and apparently overlooked the cross reference. As a hint I would suggest you move the table closer to the reference. Then at least ignorant people like me will wonder what the table is all about and actually implement abstract command for CSRs as well :-)

**Comment by timsifive** [comment]
LaTeX offers little straightforward control over where tables end up, but
I'm happy to review pull requests that improve this.
