### ISSUE TITLE
System reset

### ISSUE THREAD

**Issue by zarubaf** [riscv/riscv-debug-spec#346]
The `dmactive` says: When `1` no other mechanism should exist that may result in resetting the Debug Module after power up. 

That may be obvious to others but do you suggest that also an external (hard) reset pin can't reset the system or are you only specifying that the `ndmreset` register can not reset the DM + DTM?

**Comment by zarubaf** [comment]
I might need to add that I've implemented the first option (assuming there is a PoR circuit) but its quite convoluted and I don't like it too much. 

P.S.: Thanks for all your work

**Comment by timsifive** [comment]
I feel that if there's a real reset pin, then it's OK to reset absolutely everything. Perhaps @mwachs5 has more insight here. She's put much more thought into reset than I have.

**Comment by mwachs5** [comment]
I'd say that if you are interested in allowing users to debug across an external system reset, then that external system reset can't reset DM + DTM. But it is definately harder to provide that capability as you do need some OTHER reset (as you said, like a POR) to reset the DM and DTM.

**Comment by timsifive** [comment]
The language that specifically includes the system reset as not resetting the DM, was added in c08486f08fcbb3f9e0542dad83670df6f043be4d. I'm inclined to change that to only suggest that external global reset excludes the DM, because reset can get quite complex and is highly implementation-dependent.
