### ISSUE TITLE
Must we standardize the JTAG Header?

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#356]
I've gotten a lot of non-GitHub-based feedback on the  JTAG header we are proposing. I think it would be better to not standardize anything at this time than to standardize something that has received a lot of complaints. 

Thoughts?

**Comment by timsifive** [comment]
Is there a clear preferred alternative? We could change our recommendation, or recommend one of the two.

If we don't recommend anything, then there will be more different connectors in use, which seems bad overall.

**Comment by mwachs5** [comment]
Addressed by #375
