### ISSUE TITLE
Two typo or problems of description

### ISSUE THREAD

**Issue by poweihuang17** [riscv/riscv-debug-spec#36]
1. Table of page 40 is out of boundary and it's probably a latex problem.
2. In page 29 for serial port, the spec said "Overflow state is sticky, and can be reset by writing 0 to this bit.". What does it mean by sticky?

**Comment by mwachs5** [comment]
ssue 1 is the same as #3 , right?

Sticky means that it can *only* be reset by writing 0 to this bit. I think we should change all these "write 0 to clear" to be "write 1 to clear" as noted in #33. But at the same time we can clarify the meaning of "sticky".

**Comment by poweihuang17** [comment]
Yes, thanks for your reply.

**Comment by poweihuang17** [comment]
I agree with "write 1 to clear", because "write 0 to clear" is too awkward.

**Comment by mwachs5** [comment]
38cb5a0b  should clarify this. Let me know if the rewording makes sense.
