### ISSUE TITLE
does abstract register access while running imply it's supported while halted?

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-debug-spec#365]
Currently the spec says:
> If this command is supported for a register while the hart is running, it must also be supported for a register while the hart is halted.
> Each individual register (aside from GPRs) may be supported differently across read, write, and *halt status*.

The first sentence (from 523c64af0dc525deb5a7d0393156c4ae30d301d8) says yes while the second (from 79ffbb9bd39c63c57babfea13954866c6cc1f838) says no.

I'm inclined to say the answer is no, and delete the first sentence. What do you think?

**Comment by mwachs5** [comment]
fine by me
