### ISSUE TITLE
PDF version of draft spec no longer available?

### ISSUE THREAD

**Issue by TM1234** [riscv/riscv-debug-spec#386]
This link is broken (404):

> A pre-built version of the spec is included here.
>https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-spec.pdf

Ditto for this one:

> https://www.sifive.com/documentation/risc-v/risc-v-external-debug-support/

Is there a PDF version of the draft spec available anywhere else now?

Thanks

**Comment by bdwyatt** [comment]
The draft is still available, it's just that the file name changed to better differentiate between draft and release versions. It would appear that the link in README.md hasn't been updated yet, and I assume the SiFive link is in need of a similar update.

You can find the latest draft version [here](https://github.com/riscv/riscv-debug-spec/raw/master/riscv-debug-draft.pdf).
