### ISSUE TITLE
DMI addresses for custom extensions

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-debug-spec#396]
The spec does not explicitly state which DMI addresses can be used for custom extensions.

I propose 0x1f and 0x60--0x7f. This gives a single register that's accessible with even low abits, and plenty of registers using a more normal 7 abits.

**Comment by mwachs5** [comment]
What is a "custom extension"?

**Comment by timsifive** [comment]
Some implementation-specific functionality available to the debugger. Maybe you want to expose the internals of your pipeline, for instance.
