### ISSUE TITLE
Clarifications are needed for the fields of textra CSR

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-debug-spec#410]
Two clarifications are needed for the fields of **textra** CSR.

1. textra.**svalue** and textra.**sselect** can be written in **Debug/M/S** modes; textra.**mvalue** and textra.**mselect** can be written in **Debug/M** modes.
2. textra.mvalue and mcontex comparison, when turned on, matches in **M/S/U** modes. textra.svalue and scontext comparison, when turned on, matches in **S/U** modes.

If my proposed clarifications are wrong, please let me know. Thanks.

Chuanhua

**Comment by ernie-sifive** [comment]
1. The textra register is at 0x7A3, which is in the range defined by the RISC-V Privileged Architecture as Read/write Machine CSR's.  This register is not writable in S mode.
2. I believe the intent is to check mvalue=mcontext and svalue=scontext regardless of what mode the core is in.

**Comment by timsifive** [comment]
The intro in the Trigger Registers section also says:
> The trigger registers are only accessible in machine and Debug Mode to prevent untrusted user code from causing entry into Debug Mode without the OS’s permission.

Agree that the intent is to compare value to context (when enabled) regardless of mode. This can hopefully be used to set a trigger that only applies to a specific process (svalue) running in a specific hypervisor (mvalue).

**Comment by chuanhua** [comment]
Another clarification is needed. Should we clarify the presence of textra.sselect and textra.svalue fields with the following sentence?

When S-mode is not implemented, the fields of textra.sselect and textra.svalue will not be implemented as well.

**Comment by chuanhua** [comment]
Based on your previous comments, the scontext CSR in address 0x7AA should not be written by S-mode as well. However, the description says that it can be written by S-mode. Should it be moved to a S-mode CSR address to match the description?

**Comment by timsifive** [comment]
Yes, but that would not be a backwards compatible change. I'm not sure what the right solution is here. For now I'll explicitly note that the register address would usually apply it is not writable in S-mode, even though it is.
