### ISSUE TITLE
In latest release spec, 3.6.1.2 Quick Access words are missing

### ISSUE THREAD

**Issue by RolfyYu** [riscv/riscv-debug-spec#432]
In latest release spec, 3.6.1.2 Quick Access words are missing.

The first numbered item
<< If the hart is halted, the command sets cmderr to \halt/resume" and does not continue. >>
whole sentence is gone.

**Comment by timsifive** [comment]
Looks like LaTeX eats that line. Visually it seems the Quick Access subsubsection really should be on a new page. I have no idea why LaTeX isn't doing that.
