### ISSUE TITLE
IDCODE value - free to choose IEEE1149.1-2013 has no "recommended" value!

### ISSUE THREAD

**Issue by AnttiLukats** [riscv/riscv-debug-spec#438]
IEEE1149.1-2013 says in 8.13.1 f) that IDCODE value(s)  is up to the designer.

If RISC-V debug spec recommends (0)00001 encoding, it should be clear that recommended value comes from RISC-V foundation and not from IEEE1149.1-2013 standard.

**Comment by timsifive** [comment]
I wonder where I got that idea from. In any case I can find no evidence that IEEE recommends any specific encoding. I created a PR to fix this.
