### ISSUE TITLE
ebreaks and ebreaku

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-debug-spec#453]
What happens to ebreaks and ebreaku in dcsr if S and/or U modes aren't supported?  Are those R/W bits still required to contain storage elements but they simply don't do anything?  Do those bits become hardwired?

Should these bits be declared as WARL and, if so, what is the legal/hardwired value for an unsupported mode?  (Zero seems natural and matches dcsr[14] for the unsupported mode=2.)

**Comment by timsifive** [comment]
I'm inclined to add: "This bit is wired to 0 if the hart does not support S mode." and similar for ebreaku.

How does that sound?

**Comment by pdonahue-ventana** [comment]
I think that hardwiring to 0 sounds good for unsupported modes.

Shouldn't those bits also be defined as WARL?  I think that WARL was created exactly for this type of thing.
