### ISSUE TITLE
Is Quick Access really useful?

### ISSUE THREAD

**Issue by hyf6661669** [riscv/riscv-debug-spec#479]
I have already read the examples in Appendix B.11, which show how to use quick access to perform a single memory write or change the m bit in mcontrol register of a trigger. But I think this could also be achieved by sending a ```Access Register``` command with command[transfer] = 0, command[postexec] = 1. So it seems that "Quick Access" could be replaced.

![image](https://user-images.githubusercontent.com/18757974/62202004-0a070800-b3bb-11e9-8bba-def6af9d0fdf.png)

**Comment by timsifive** [comment]
Access Register with transfer=0 postexec=1 is often used while the hart is halted to simply execute the program buffer.

Quick Access differs in that it will halt the hart before executing the program buffer, and resume it afterwards.

You're right that we could have said that Access Register transfer=0 postexec=1 preserves the running state, and behaves like Quick Access if the hart is running when the command is issued. That's not what the spec says though, and at this point would not be compatible. If this was a big problem we could probably hand-wave that away (nobody does Access Register transfer=0 postexec=1 while the hart is running). I don't see a big downside with the way the spec is written, however.
