### ISSUE TITLE
Resuming the CPU when halted due to trigger

### ISSUE THREAD

**Issue by JanMatCodasip** [riscv/riscv-debug-spec#492]
Let's assume a processor halts due to a type-2 trigger that is set to fire _before_ execution of the instruction (i.e. mcontrol.timing=0). Is my understanding correct that resuming the processor (dmcontrol.resumereq <-- 1) without disabling the trigger shall cause the trigger to be be re-activated? In other words, is it correct that PC in that case must not advance until such trigger with timing=0 is removed?

Thank you for clarification,
Jan

**Comment by timsifive** [comment]
That is right. If that trigger fires e.g. on the instruction at 0x1000, and dpc=0x1000 when resuming from Debug Mode, then the trigger will fire immediately. The instruction will not be executed.

**Comment by JanMatCodasip** [comment]
Thank you for checking my interpretation of the spec, appreciated.
