### ISSUE TITLE
What is DPC set to when single-stepping over an instruction that causes an exception

### ISSUE THREAD

**Issue by GregAC** [riscv/riscv-debug-spec#497]
In the debug spec for the 'dcsr.step' field it is stated:

'When set and not in Debug Mode, the hart will only execute a single instruction and then enter Debug Mode. If the instruction does not complete due to an exception, the hart will immediately enter Debug Mode before executing the trap handler, with appropriate exception registers set'

What isn't clear to me is what DPC should be set to when you single step a instruction that causes an exception. In my opinion it should point to the PC of the exception handler (as that is the next PC the hart would execute were it not single stepping) though the spec doesn't make this explicit

**Comment by pdonahue-ventana** [comment]
See the definition of dpc to determine what dpc is set to:
> Upon entry to debug mode, dpc is updated with the virtual address of the next instruction to be
executed.

The next instruction to be executed is the first instruction of the handler so your intuition is right.  Setting dpc to anything else wouldn't work because you'd start at the wrong place upon debug mode exit.
