### ISSUE TITLE
Can this debug architecture run step when virtual memory architecture is running ?

### ISSUE THREAD

**Issue by linkLiao** [riscv/riscv-debug-spec#518]
Hi, as title, I want to debug the rocket chip processor when it run linux system, but I can't run step debug for it because of virtual address is not different from physical address, what should I do to solve this problem??

**Comment by timsifive** [comment]
I assume that you are single stepping by setting a breakpoint on the next instruction and you're not using external debug. In that case the spec defines a trigger that fires after a certain number of instructions have been executed. I do not know if Rocket implements that trigger.

**Comment by timsifive** [comment]
Closing due to lack of response.
