### ISSUE TITLE
ICount Trigger Type TODO

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-debug-spec#52]
There is still a TODO about icount trigger type, also related to https://github.com/sorear/riscv-specs/issues/21

**Comment by mwachs5** [comment]
TODO: Check in with @aswaterman and @sorear about this and whether we can remove the TODO.

**Comment by timsifive** [comment]
Even though nobody has implemented this, this is a potentially important feature because it is the only simple way that a debugger running natively on a RISC-V platform can perform a single step.

**Comment by mwachs5** [comment]
Closed by #173
