### ISSUE TITLE
aampostincrement - mandatory or optional?

### ISSUE THREAD

**Issue by JanMatCodasip** [riscv/riscv-debug-spec#531]
Bit `aampostincrement` (Abstract Memory Access) is not described as "mandatory" or "optional" in the Spec 0.13.2. Does that mean that its full support is mandatory?

Note: Several other abstract command related bits (e.g. `aarpostincrement`, `postexec`) are explicitly marked as "optional". Therefore it is not unreasonable to think that bits where "optional" is not explicitly mentioned are required. Can you clarify whether this is how the spec was meant to be interpreted?

Thank you.

**Comment by timsifive** [comment]
`aampostincrement` is optional. I'll clarify the spec.

**Comment by JanMatCodasip** [comment]
Thanks for clarifying this.
