### ISSUE TITLE
clarification of completion of program buffer is output for fence

### ISSUE THREAD

**Issue by silabs-PaulZ** [riscv/riscv-debug-spec#533]
Hi @timsifive ,

I have some clarification questions regarding rule 9) in Chapter 4 RISC-V Debug, Section 4.1:
[“Completing Program Buffer execution is considered output for the purpose of fence instructions.”](https://github.com/riscv/riscv-debug-spec/blob/2210002c3724a2f91c63900eb79acfcceeaf4c40/core_debug.tex#L38)

Here is a copy of the riscv-spec section 2.7 Memory Ordering Instructions on the FENCE instruction for reference:
_The FENCE instruction is used to order device I/O and memory accesses as viewed by other RISCV
harts and external devices or coprocessors. Any combination of device input (I), device output
(O), memory reads (R), and memory writes (W) may be ordered with respect to any combination
of the same. Informally, no other RISC-V hart or external device can observe any operation in the
successor set following a FENCE before any operation in the predecessor set preceding the FENCE._

Are the following statements and my understanding correct:
From the debug requirement 9), an exit of the program buffer will set an internal ‘device output’ type flag. An ensuing FENCE instruction will then order the next successor access if it is dependent on a predecessor ‘device output’ access type. Flag is cleared if access has completed.

Exiting the program buffer can be accomplished with:
•	ebreak (jump back to debug halt address)
•	dret (exit debug and jump back to main execution)
•	exception (jump to debug exception address)

Also, can you clarify [‘this address'](https://github.com/riscv/riscv-debug-spec/blob/2210002c3724a2f91c63900eb79acfcceeaf4c40/implementations.tex#L57) in sectionA.2 Execution Based. Is 'this address' assumed to be the address of the DM or the debug exception address? I would assume that all access to DM be an I/O for fence instruction.

Regards,
-PaulZ

**Comment by timsifive** [comment]
Can you see if #601 clears things up?
