### ISSUE TITLE
How many custom DM registers are there?

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-debug-spec#558]
Are there 3 custom DM registers (custom, custom0, custom15) or are there 17 (custom, custom0 through custom15)?  The spec says the former but I suspect that the intention may be the latter.

**Comment by ernie-sifive** [comment]
I suspect the intention was to reserve the whole range custom0 through custom15.

**Comment by timsifive** [comment]
Fixed by #579.
