### ISSUE TITLE
Make list of functional changes between 0.13 and 1.0

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-debug-spec#584]
Highlight the backwards incompatible changes.

**Comment by JamesKenneyImperas** [comment]
I have a list of things that have changed for the trigger module in front of me. I'm certain that you know this better that I do, but I'll jot them down as a reminder:

1. scontext CSR address reassigned to 0x5a8;
2. hcontext CSR introduced at 0x6a8 as alias of mcontext when H present;
3. optional mscontext CSR in old scontext CSR location;
4. vu and vs added to icount, itrigger and etrigger trigger types when H present;
5. new trigger type mcontrol6;
6. new match types 8, 9, 12, 13;
7. textra32/textra64 mvalue/mselect renamed mhvalue/mhselect, and functionality expanded when H present;
8. textra32/textra64 sselect filtering by vsatp.ASID where appropriate;
9. tcontrol.sxce and tcontrol.hcxe added (backwards incompatible).
