### ISSUE TITLE
sw_registers.txt

### ISSUE THREAD

**Issue by donbmouse** [riscv/riscv-debug-spec#61]
Hello,

I'm starting to merge my security stuff but I can't build with the latest pull. 
0512f5d9e9f80b392b91ca32c17f493544820302

I get the following error:
$ make
./registers.py --custom --definitions jtag_registers.tex.inc --cheader jtag_registers.h xml/jtag_registers.xml > jtag_registers.tex
./registers.py --custom --definitions core_registers.tex.inc --cheader core_registers.h xml/core_registers.xml > core_registers.tex
./registers.py --custom --definitions hwbp_registers.tex.inc --cheader hwbp_registers.h xml/hwbp_registers.xml > hwbp_registers.tex
./registers.py --custom --definitions dm_registers.tex.inc --cheader dm_registers.h xml/dm_registers.xml > dm_registers.tex
./registers.py --custom --definitions trace_registers.tex.inc --cheader trace_registers.h xml/trace_registers.xml > trace_registers.tex
./registers.py --custom --definitions sample_registers.tex.inc --cheader sample_registers.h xml/sample_registers.xml > sample_registers.tex
./registers.py --custom --definitions abstract_commands.tex.inc --cheader abstract_commands.h xml/abstract_commands.xml > abstract_commands.tex
make: *** No rule to make target 'sw_registers.tex', needed by 'riscv-debug-spec.pdf'.  Stop.

**Comment by mwachs5** [comment]
Oops, I forgot to add the file on the last commit. Will try to remedy this
as soon as possible.
