### ISSUE TITLE
License of generated headers?

### ISSUE THREAD

**Issue by jmerdich** [riscv/riscv-debug-spec#618]
The `debug_defines.h` is currently spit out without any license attached, which is a Bad Thing. That should be explicitly marked as CC-BY-4.0 or released under a license more suitable for code (riscv-opcodes uses BSD-3, for example).

Not causing any issues now, but I've dealt with lawyers enough to want to nip this in the bud.

**Comment by pdonahue-ventana** [comment]
You cite riscv-opcodes.  The header file there just says `/* See LICENSE for license details. */`.  Do you think that's sufficient?  (That doesn't seem very self-contained to me.)
