### ISSUE TITLE
Clarification - Section 1.4 list

### ISSUE THREAD

**Issue by donbmouse** [riscv/riscv-debug-spec#62]
Can the language in the list in section 1.4 be changed so that it is more clear which lines are optional? When a line reads "can do X", is the intent to say "is capable of" or "can choose to"? If an extension is optional, it should occupy a line at the end of the list to group optional lines together. Otherwise, upon reading "option" in line 4 the perception of "can do X" can waver by the reader's perception.

**Comment by mwachs5** [comment]
The list in 1.4 was more "here's what this spec covers". I think it was a holdover from the 'this vs that' spec discussions, and may not really be necessary any more. Right now there are 3 roughly equivalent lists in the spec, which we may want to combine/eliminate/mark as 'commentary':

1.3 aka "What a HW debugger is useful for"

1.4 aka "What this spec covers"

3 aka "What a Debug Module has to do"

And yes I just created a list complaining about how many lists are in the spec ;)
