### ISSUE TITLE
"Latest draft" link is broken

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [riscv/riscv-debug-spec#626]
The "latest draft" link (https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-draft.pdf) in this section:

https://github.com/riscv/riscv-debug-spec#risc-v-debug-specification

is broken.

**Comment by timsifive** [comment]
There is no current draft. There's only a current stable. I'll update the README

**Comment by TommyMurphyTM1234** [comment]
Thanks @timsifive 👍
