### ISSUE TITLE
Clarification - 1.4 #11,13 Hart vs Core

### ISSUE THREAD

**Issue by donbmouse** [riscv/riscv-debug-spec#63]
In section 1.4, list numbers 11 and 13, does the author mean **hart** or all available harts? Presuming "all available harts" because the term "core" is used, but is it desirable for all harts to be stopped on a breakpoint? How does the masking of certain harts in a (core) affect these list items?

**Comment by mwachs5** [comment]
Right now there is no way in the spec to halt all (or any other) harts when a breakpoint is hit (this would presumably be done by SW if desired once the hart is observed to have hit the breakpoint).

This is certainly an interesting feature, but it's not currently defined. It seems like its definition might belong in the Trigger register vs. the debug module.

But for this particular issue we should change the language to say 'hart' not 'core'.
