### ISSUE TITLE
Nomenclature suggestion: use xepc, xcause etc

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-debug-spec#652]
To describe trap behavior when breakpoint exceptions have been delegated from Machine mode, the specification is using the imprecise term "exception PC" where it used to say `mepc`. The Fast Interrupt specification uses terminology `xepc`, `xcause` etc in this context, which I think is more precise and preserves the link with the CSR name better. I think it would improve things to adopt this naming convention.

**Comment by pdonahue-ventana** [comment]
We had a short debate about this: https://github.com/riscv/riscv-debug-spec/pull/637#pullrequestreview-674761467

I'm OK with xepc and xcause.  The priv spec itself refers to xepc in 3.3.2.

**Comment by timsifive** [comment]
The latest github version of the privspec does not use xepc, except in the Preface to Version 1.11.

It seems like a reasonable term to use. If we switch to it we should define it in the Terminology section.

**Comment by pdonahue-ventana** [comment]
The current version uses xepc here: https://github.com/riscv/riscv-isa-manual/blob/master/src/machine.tex#L2432

**Comment by timsifive** [comment]
Thanks for that pointer. My search for "xepc" didn't turn it up. In that case let's use it to be consistent with the other specs.
