### ISSUE TITLE
sw_registers.tex is missing

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv/riscv-debug-spec#67]
````
$ make -j1
make: *** No rule to make target 'sw_registers.tex', needed by 'riscv-debug-spec.pdf'.  Stop.
````

It looks like this is from 0512f5d9e9f80b392b91ca32c17f493544820302.

**Comment by donbmouse** [comment]
Duplicate of #61.

**Comment by mwachs5** [comment]
yeah sorry can't get onto github right now. Can you just 'touch' the file
and add it for now?

**Comment by palmer-dabbelt** [comment]
I tried already, it blows up.  Where is your workdir?

**Comment by mwachs5** [comment]
Ok sorry it's on my laptop. Can you just do a "revert" of the change that
added that file through github? I realize I forgot to actually delete the
old code anyway so no information is lost.

**Comment by mwachs5** [comment]
Wait never mind, I'll just make a PR that actually fixes the issue.
