### ISSUE TITLE
B8.1 (Writing Memory) Using System Bus Acces

### ISSUE THREAD

**Issue by UweBonnes** [riscv/riscv-debug-spec#671]
The first example shows writing a word to memory, Is this always a word transfer independent of the sbaccess value in sbcs or needs sbcs to be set according to the wanted transfer width?

**Comment by timsifive** [comment]
Good catch. The access size depends on sbcs.sbaccess.

**Comment by UweBonnes** [comment]
Thanks for the confirmation. But now If found out that the ESP32-C3  i tested only know about 32 bit access.
