### ISSUE TITLE
clarify behavior of dmi[address] when in capture-DR

### ISSUE THREAD

**Issue by allexoll** [riscv/riscv-debug-spec#678]
in section 6.1.5 Debug Module Interface Access, 

`dmi[data]` is specified both in capture-DR and in update-DR (read & write)
same goes for `op`

but `address` is only specified for update-DR, and no mention is made of what it should be when in capture-DR (or if it is ignored, but i think we should specify it too?)

**Comment by pdonahue-ventana** [comment]
I think that this was addressed (pardon the pun) in https://github.com/riscv/riscv-debug-spec/pull/762.

**Comment by allexoll** [comment]
yes it is, closing this, thanks!
