### ISSUE TITLE
Why should hardware clear the action field whenever the action field is 1?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-debug-spec#746]
Hello,

I cannot understand the following compound sentence with five clauses. Can you share some words on that?
![image](https://user-images.githubusercontent.com/39526191/184765305-1fc3c453-de2e-4b76-a1ca-7de2a1225422.png)

Thank you
Best regards,
YenHaoChen

**Comment by pdonahue-ventana** [comment]
It's illegal to have action=1 and dmode=0 (as specified in the previous sentence) so the suggestion is that WARL sanitization should clear action rather than setting dmode.

**Comment by YenHaoChen** [comment]
Thank you for clarification.
