### ISSUE TITLE
Data bitfield inside dmi register

### ISSUE THREAD

**Issue by ToTamire** [riscv/riscv-debug-spec#760]
What JTAG should read after successfull write transaction on debug module interface? I mean when JTAG do next scan chain to read dmi register and it's op bitfield returns 0 (previous operation completed successfully). Data bitfield in dmi register should contain: written data, register value before write or register value after write?

**Comment by timsifive** [comment]
Hmm... the spec is quite unclear about this. I don't think it matters what dmi.address and dmi.data contain after a write. I made #762 to try to clarify, and get feedback on what we really want to say.

**Comment by pdonahue-ventana** [comment]
#762 is merged.
