### ISSUE TITLE
sbasize bitfield inside sbcs register

### ISSUE THREAD

**Issue by ToTamire** [riscv/riscv-debug-spec#761]
Maximum value allowed by sbasize bitfield inside sbcs register is 127. Maximum value should be 128 to support sbaddress[127:0].

**Comment by pdonahue-ventana** [comment]
Sv32 only supports addresses up to 34 bits.  Sv39/48/57 support up to 56 bits.  RV64 could support up to 64 bits in bare mode.  The only way you can have more than 64 physical address bits is with RV128.  That's not standardized yet.  Even when it is, I think that 128 trillion yottabytes (2^127 bytes) will be sufficient for a while.  Adding support for that 128th address bit is not urgent.

**Comment by pdonahue-ventana** [comment]
There are less than 2^93 atoms in the observable universe so I don't think that limiting our physical address space to 2^127 is unreasonable.
