### ISSUE TITLE
Typo in JTAG connector pinout

### ISSUE THREAD

**Issue by JanMatCodasip** [riscv/riscv-debug-spec#763]
Pins 18 and 20 of the JTAG connector are labelled:

- DBGRQ and DBGACK in Table 6.6
- TRIGIN and TRIGOUT in Table 6.7

I assume this is a typo. Which names are the correct ones?

Thank you.

![image](https://user-images.githubusercontent.com/50193733/196175293-c9042bbe-9788-4bab-8c59-35e85203d90f.png)

**Comment by timsifive** [comment]
This was fixed by #664.
