### ISSUE TITLE
Do Etrigger and Itrigger provide functionality beyond that of a PC trigger?

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-debug-spec#775]
Given that a PC trigger (sel=0, exec=1, match=0) can be used to stop (generate a breakpoint exception or enter debug mode) before the first instruction of a trap handler, what additional functionality is provided by etrigger/itrigger?  Why not simplify the spec by removing etrigger/itrigger or placing them in an appendix?

**Comment by pdonahue-ventana** [comment]
etrigger can filter on the mode that caused the exception and on specific exception types.  PC triggers are only able to stop when you enter a particular handler.  All synchronous exceptions go to the same vector and, unless you're in Vectored mode, all asynchronous interrupts go there, too.  If you're debugging illegal instructions in U mode, it's nicer to only stop if you actually hit an illegal instruction in U mode.  With the PC trigger on the vector, you'd potentially stop every time you got an interrupt, page fault, misaligned load, ecall, etc.

It's true that you could set a PC trigger at a subhandler that runs after mcause has been parsed, though setting such a trigger would require you to understand the initial handler code and trust it to be bug-free.

**Comment by jrahmeh** [comment]
Thanks for the clarification.  Closing issue.
