### ISSUE TITLE
Will AMO fire on a chain with a load-only trigger and a store-only trigger?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-debug-spec#780]
Consider a trigger chain consisting of two triggers—one only matches on loading address _A_, and the other only matches on storing address _A_.
Load access matches the first load-only trigger but does not the second store-only one, and store access does not match the first load-only trigger but does the second store-only one. Thus, both normal load and store do not match the chain.

How about an AMO instruction on address _A_? An AMO is both load and store, and, thus, matches both triggers in the chain. Does this mean AMO instructions can fire on such a chain with a load-only trigger and a store-only trigger?

**Comment by timsifive** [comment]
> Does this mean AMO instructions can fire on such a chain with a load-only trigger and a store-only trigger?

Yes, that's how I read the spec.

**Comment by YenHaoChen** [comment]
Thank you
