### ISSUE TITLE
Behavior of W1 fields

### ISSUE THREAD

**Issue by MarekPesta** [riscv/riscv-debug-spec#787]
Hello I've a question about W1 fields, especially about `dmcontrol.resumreq`. As defined in spec the W1 is:

> Write-only. Only writing 1 has an effect. When read the returned value should be 0.

According to #321 after  `dmcontrol.resumreq` is set it doesn't require to be cleared to write 1 to it again and to perform a resume request. But B.2.4 (spec) states:

> ... Then it can let the selected harts run by setting `resumereq`. Once `allresumeack` is set, the debugger knows the hart has resumed, *and it can clear `resumereq`*. ...

Spec states that writing 1 to W1 takes effect and it should be red as 0. But it does not explicitly say that W1 doesn't have to be cleared after writing 1. In fact, B.2.4 suggests that it should be cleared before next write. My question is, how should the DM behave? It should expect the debugger to clear W1 field (in this case `dmcontrol.resumreq`) or it should assume that W1 field must be cleared internally (by the DM) after successful request?

**Comment by timsifive** [comment]
The appendix is wrong. I'll update it. Thanks for pointing this out.
