### ISSUE TITLE
Question about Table 5.10 Suggested Trigger Timings

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-debug-spec#792]
Table 5.10 gives suggested trigger timings. I am confused about the terminology "Address+Data" ("Address+Instruction") in the table. The "Address" and "Data" ("Instruction") are controlled by the same bit "select" and can only be either one. What does the "+" sign mean? Does it mean "or"?

Additionally, the table only gives suggested trigger timing for execute-only, load-only, and store-only triggers with {execute,store,load} in {{1,0,0}, {0,0,1}, {0,1,0}}. Do we have suggested trigger timing for mixed triggers with {execute,store,load} in {{1,1,0}, {1,0,1}, {0,1,1}, {1,1,1}}?

```
Match type                  (Encoding)                               | Suggested trigger timing
-----------------------------------------------------------------------------------------------
execute address             (select=0, {execute,store,load}={1,0,0}) | before (timing=0)
execute instruction         (select=1, {execute,store,load}={1,0,0}) | before (timing=0)
execute address+instruction (select=?, {execute,store,load}={1,0,0}) | before (timing=0)
load address                (select=0, {execute,store,load}={0,0,1}) | before (timing=0)
load data                   (select=1, {execute,store,load}={0,0,1}) | after  (timing=1)
load address+data           (select=?, {execute,store,load}={0,0,1}) | after  (timing=1)
store address               (select=0, {execute,store,load}={0,1,0}) | before (timing=0)
store data                  (select=1, {execute,store,load}={0,1,0}) | before (timing=0)
store address+data          (select=?, {execute,store,load}={0,1,0}) | before (timing=0)
```

![image](https://user-images.githubusercontent.com/39526191/210475419-d260b1cb-8362-4faf-b4a1-588c7eed6c82.png)

**Comment by scottj97** [comment]
Perhaps the address+data is referring to a chain of triggers? Below Table 5.10 is this line:

> A chain of triggers that don’t all have the same timing value will never fire. That means to implement the suggestions in Table 5.10, both timings should be supported on load address triggers.

**Comment by pdonahue-ventana** [comment]
Yes, this has to do with chaining.  If you only trigger on a load address, use timing=before.  If you only trigger on a load data value, use timing=after.  If you have a chain that fires only when you load particular data value from a particular address then use timing=after.

**Comment by YenHaoChen** [comment]
Thanks for the reply. Do we have suggested timing for ```select=1(data), {execute,store,load}={1,0,1}```, ```select=1(data), {execute,store,load}={0,1,1}```, and ```select=1(data), {execute,store,load}={1,1,1}```?

**Comment by pdonahue-ventana** [comment]
I think that there is no suggested timing for those since there is no single timing that provides "the best user experience."

**Comment by YenHaoChen** [comment]
Thank you
