### ISSUE TITLE
Can abstract commands size be grater that XLEN

### ISSUE THREAD

**Issue by hananyasegal1** [riscv/riscv-debug-spec#803]
Hi,

I want to ask if according to debug spec, is it possible that abstract command may be with 64 bits size and the XLEN can be 32 bits for example?
Does it depend on debug spec version?

Thanks,
Hananya

**Comment by timsifive** [comment]
The abstract command register (`command`) is always 32 bits wide, regardless of the harts the Debug Module is attached to. I don't think this was ever any different.

**Comment by pdonahue-ventana** [comment]
I think that the question is whether you can have aarsize=3 (64-bit) when XLEN=32.  I believe that this would be supported on RV32D implementations.

**Comment by pdonahue-ventana** [comment]
Nothing in the aarsize section says anything about XLEN.  It's all about the size of the register being accessed.  If you think that the spec is misleading or confusing then please reopen.
