### ISSUE TITLE
Unclear xepc value for mcontrol trigger with action=0 and timing=0

### ISSUE THREAD

**Issue by silverscampi** [riscv/riscv-debug-spec#814]
5.5.11 Match Control (mcontrol, at 0x7a1) table says:
timing: 0 (before): "xepc or dpc (depending on action) must be set to the virtual address of the instruction that matched."

and Table 5.1: action encoding says:
Value 0: "xepc must contain the virtual address of the next instruction that must be executed to preserve the program flow."

So, if we have hit an mcontrol trigger with timing=0 and action=0, what should xepc contain? The virtual address of the matched instruction, or of the next instruction after it to be executed?

**Comment by timsifive** [comment]
Your understanding is correct.
