### ISSUE TITLE
Privilege mode for park loop

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-debug-spec#815]
Section A.2 second paragraph states that "This jump is similar to a trap but is not architecturally considered a trap ...".  What is the privilege mode after this jump?  Is the privilege mode unchanged or does it become M like it does for a trap?

**Comment by pdonahue-ventana** [comment]
> What is the privilege mode after this jump?

Two sentences before, it says that the hart enters debug mode before doing the jump.

**Comment by pdonahue-ventana** [comment]
Reopen if this is still confusing.
