### ISSUE TITLE
Is virtual mode restored by dret?

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-debug-spec#817]
Section A.2 states "When dret is executed, pc is restored from dpc and normal execution resumes at the privilege set by prv."
How come the virtual (V) mode is not restored from the DCSR.V bit?

**Comment by pdonahue-ventana** [comment]
The normative part of the spec says that "When a hart resumes ... [t]he current privilege mode and virtualization mode are changed to that specified by prv and v."  The (non-normative) sentence you quoted wasn't updated when hypervisor support (including dcsr.v) was added to the spec, though that should be fixed.

**Comment by jrahmeh** [comment]
Thank you.  Closing.
