### ISSUE TITLE
When trigger(load/store, action=1) match vector load/store instruction's element address,  should entry into Debug Mode?

### ISSUE THREAD

**Issue by GZYyyyy** [riscv/riscv-debug-spec#822]
If any element of the vector load/store instruction matches the set trigger breakpoint, do I enter debug mode? The debug register information is saved for the vector instruction? For example, dpc holds the next vector instruction.

**Comment by timsifive** [comment]
Very recently this clarification was added: https://github.com/riscv/riscv-debug-spec/blob/master/Sdtrig.tex#L269
I think that answers your first question.

I made https://github.com/riscv/riscv-debug-spec/pull/823 which hopefully answers your second question.

If not, let me know.

**Comment by GZYyyyy** [comment]
Thank you.
