### ISSUE TITLE
Can DPC be updated on all committed instructions?

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-debug-spec#824]
The debug spec says:

`Upon entry to debug mode, dpc is updated with the virtual address of the next instruction to be executed.`

This doesn't preclude updating DPC at other times. In particlar I'm interested in allowing the debugger to monitor the current PC without halting the core, and reading DPC seems like a sensible way to achieve this.

Can there be a non-normative note added to the debug spec saying that this is legal behaviour?

Thanks

**Comment by pdonahue-ventana** [comment]
Sure.  Tim created #825.

**Comment by pdonahue-ventana** [comment]
#825 is now merged.
