### ISSUE TITLE
Is an address mcontrol/mcontrol6 trigger valid to compare subset of the other addesses?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-debug-spec#877]
Hello, 

The specification requires an address mcontrol/mcontrol6 trigger to compare the lowest address and recommends comparing other accessed addresses. For example, consider a 4-byte memory access with the lowest address 0x4000. An address trigger is required to compare address={0x4000} and recommanended to compared address={0x4000, 0x4001, 0x4002, 0x4003}.

Is it valid to compare an arbitrary subset of the other addresses? For the above case, is comparing address={0x4000, 0x4002} only valid? (Although this does not make sense from a user perspective, I cannot find a solid answer from the text of the specification.)

![image](https://github.com/riscv/riscv-debug-spec/assets/39526191/33d040d7-df74-40e6-b0a3-ab497f78d76e)

Update 2023.09.19:
A follow-up question. Consider misaligned 4-byte access at address 0x3fff on the following designs:
  - Design A) Match address trigger with tdata2={0x3fff} (required)
  - Design B) Match address trigger with tdata2={0x3fff, 0x4000, 0x4001, 0x4002} (recommended)
  - Design C) Match address trigger with tdata2={0x3fff, 0x4000}

Are all of the above designs valid?

**Comment by timsifive** [comment]
My reading is that they are all valid. However, if you want to make a product that is useful to people then design C would be very confusing. The spec is intentionally a bit vague here because implementing triggers can be expensive, because comparators are sizable and might be on the critical path. It's better to implement something suboptimal than to implement nothing at all.

**Comment by YenHaoChen** [comment]
Thank you

**Comment by pranjal20498** [comment]
if my tdata2 is the same as any load address value then it would take trigger for match=0?

**Comment by rtwfroody** [comment]
@pranjal20498, yes, that is the preferred behavior.
