### ISSUE TITLE
Does "this section" mean "this chapter"?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-debug-spec#894]
Section 4.1, "Debug Mode", says:
> All implemented instructions operate just as they do in M-mode, unless an exception is mentioned in this section.

Does "this section" mean just Section 4.1, as would seem to be the literal interpretation, or does it mean all of Chapter 4 (Sdext)?

**Comment by timsifive** [comment]
@jhauser-us, if this change addresses your feedback, can you close this issue?
