### ISSUE TITLE
Is mcontrol6 trigger allowed to fire on prestart, inactive, and tail elements of vector load/store?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-debug-spec#914]
Hello,

I want to clarify the behavior of mcontrol6 with uncertainen=1, action=0 and its interaction with the vector spec. 

According to the vector spec, the prestart, inactive, and tail elements of vector load/store do not raise exceptions. On the other hand, the debug spec states that mcontrol6 with uncertainen=1 will match if it’s possible that it would match perfectly, which means, for any memory address, whether to raise a breakpoint exception with action=0 is a hardware-dependent behavior. These two statements seem to conflict with each other. Can anyone share some words about this?

In this case, I guess the debug spec takes priority over the vector spec because the vector spec is unprivileged while the debug spec is privileged. As a result, mcontrol6 with uncertainen=1 should be allowed to raise a breakpoint exception on prestart, inactive, and tail elements of vector load/store. Is this correct?

Thank you.

Best regards,
YenHaoChen

![image](https://github.com/riscv/riscv-debug-spec/assets/39526191/7e944149-5cd2-4a22-a262-735be8538fb3)

**Comment by pdonahue-ventana** [comment]
There was a [huge email thread](https://lists.riscv.org/g/tech-debug/topic/94864865) about mcontrol6 and the V extension.  I think that the idea of uncertainen started around here: https://lists.riscv.org/g/tech-debug/message/1040

I think that the net result is that prestart, inactive, and tail elements are allowed to raise breakpoint exceptions.

**Comment by YenHaoChen** [comment]
Thank you.
