### ISSUE TITLE
Clarification on updating the uncertain bit

### ISSUE THREAD

**Issue by larryrong** [riscv/riscv-debug-spec#915]
Hello, 

In the debug spec - ch.5.6.12 Match Control Type 6
...
uncertain -> This bit should be updated every time that hit0 or hit1 is updated.
...

The uncertain bit will be updated when one of the hit bits is updated. In this scenario, the debug specification permits us not to implement hit bits, and, consequently, hit bits are never asserted. Does this make sense? I believe the condition for updating the uncertain bit should be 'The TM updates this field when the trigger fires.'

Best regards,
Larry

**Comment by timsifive** [comment]
Thanks for pointing that out.
