### ISSUE TITLE
what does haltsum0: LSB/MSB mean?

### ISSUE THREAD

**Issue by pengfei842852593** [riscv/riscv-debug-spec#921]
SPEC: 3.12.14 The LSB reflects the halt status of hart {hartsel[19:5],5’h0}, and the MSB reflects halt status of hart {hartsel[19:5],5’h1f}
What does this mean? I don't understand the {hartsel[19:5],5’h0} and {hartsel[19:5],5’h1f}. 
Can anyone help me?

**Comment by bdwyatt** [comment]
Haltsum0 will show the halt status of up to 32 harts, and in the case of a design with more than 32 harts, the upper 15 bits hartsel are used to index further into the harts attached to the debug module.

For example, if hartsel[19:5] = 0, hartsum0 will show the halt status of harts 0(lsb) - 31(msb). If hartsel[19:5] = 2, you'd see the halt status for harts 64 - 95.
