### ISSUE TITLE
Clarify the feature of reset

### ISSUE THREAD

**Issue by wissygh** [riscv/riscv-debug-spec#923]
Hi~, when reading about the feature in the spec, I am kind of confused.  Could you please clarify the specification for the following feature(in chapter 3)：

6. Provide a mechanism to allow debugging harts immediately out of reset (regardless of the reset cause). (Optional) 

thanks.
![feature](https://github.com/riscv/riscv-debug-spec/assets/41678041/b191b85a-cdfc-482c-ac19-d40c955cc4d9)

**Comment by timsifive** [comment]
This specifically refers to the behavior when haltreq is set when a hart comes out of reset. It's mentioned in this list because for some people using a debugger it's important that they can debug code before it executes even a single instruction.

**Comment by wissygh** [comment]
Thanks. Could you  please also clarify difference between number “5” and number “6” in the list? What are the respective scenarios for each of them? In addition, I saw that number “6” is added with _ hasresethaltreq_  #255 .

**Comment by pdonahue-ventana** [comment]
Item 6 describes a feature that allows you to stop on the first instruction after reset.  Item 5 ("Provide access to a reset signal") describes a mechanism for resetting the hart, where that reset signal honors the mechanism in item 6.  Some other reset mechanism (e.g. power-on reset which resets the whole chip and loses all state) might not allow you to stop on the first instruction after reset.

Item 5 is hartreset and item 6 is resethaltreq (both accessed via dmcontrol).

**Comment by wissygh** [comment]
> Item 6 describes a feature that allows you to stop on the first instruction after reset. Item 5 ("Provide access to a reset signal") describes a mechanism for resetting the hart, where that reset signal honors the mechanism in item 6. Some other reset mechanism (e.g. power-on reset which resets the whole chip and loses all state) might not allow you to stop on the first instruction after reset.
> 
> Item 5 is hartreset and item 6 is resethaltreq (both accessed via dmcontrol).

Thanks a bunch! I reckon I've got it now.
