### ISSUE TITLE
"$" characters in asciidoc

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-debug-spec#964]
I randomly reviewed page 85 and found this LaTeX remnant:
> The behavior is only well-defined if $select=0$, or if the access size is XLEN.

I searched the asciidoc version for "$" and found several other stray "$" characters.

**Comment by rtwfroody** [comment]
Thank you!

**Comment by wmat** [comment]
Does the merge of #965 warrant closing this issue?
