### ISSUE TITLE
Duplicate register field layout diagram for `tdata1`

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [riscv/riscv-debug-spec#989]
Is the duplicated/repeated register layout diagram here simply an oversight?

![Screenshot_20240322-074927](https://github.com/riscv/riscv-debug-spec/assets/14550604/8d1078e8-9392-4e32-bb44-499b736a5a7d)

Seen in 1.0.0-rc2: 

* https://github.com/riscv/riscv-debug-spec/releases/tag/1.0.0-rc2

**Comment by rtwfroody** [comment]
Good catch. Thanks.
